tasks:
  - init: |
      npm install
      gp sync-done npminstall
    command: echo

vscode:
  extensions:
    - "elmtooling.elm-ls-vscode"
    - "hbenl.vscode-test-explorer"
    - "hbenl.test-adapter-converter"
